In [1]:
#import torch
import sys
sys.path.append('..')

import numpy as np
import polars as pl
import pandas as pd
from rdkit import Chem
from rdkit.Chem import AllChem
from utils.utils import get_data_from_parquet, save_data_to_parquet

/Users/a2251/Documents/IT_Dev/ujSem3/machineLearning/spark_airflow/chembl_env/lib/python3.12/site-packages/chembl_webresource_client/__init__.py:4: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  __version__ = __import__('pkg_resources').get_distribution('chembl_webresource_client').version

In [4]:
df = get_data_from_parquet("Chembl203_with_molecule_and_activity.parquet")

Wczytywanie danych z pliku lokalnego: Chembl203_with_molecule_and_activity.parquet

In [5]:
df.describe()

shape: (9, 58)
┌────────────┬────────────┬────────────┬────────────┬───┬────────┬─────────┬───────────┬───────────┐
│ statistic  ┆ action_typ ┆ activity_c ┆ activity_i ┆ … ┆ psa    ┆ mw      ┆ ecfp_smil ┆ fingerpri │
│ ---        ┆ e          ┆ omment     ┆ d          ┆   ┆ ---    ┆ ---     ┆ es        ┆ nt        │
│ str        ┆ ---        ┆ ---        ┆ ---        ┆   ┆ str    ┆ str     ┆ ---       ┆ ---       │
│            ┆ f64        ┆ str        ┆ f64        ┆   ┆        ┆         ┆ f64       ┆ f64       │
╞════════════╪════════════╪════════════╪════════════╪═══╪════════╪═════════╪═══════════╪═══════════╡
│ count      ┆ 96532.0    ┆ 40806      ┆ 291187.0   ┆ … ┆ 290229 ┆ 291187  ┆ 291187.0  ┆ 291187.0  │
│ null_count ┆ 194655.0   ┆ 250381     ┆ 0.0        ┆ … ┆ 958    ┆ 0       ┆ 0.0       ┆ 0.0       │
│ mean       ┆ null       ┆ null       ┆ 1.9456e7   ┆ … ┆ null   ┆ null    ┆ null      ┆ null      │
│ std        ┆ null       ┆ null       ┆ 7.3185e6   ┆ … ┆ null   ┆ null    ┆ null      ┆ null      │
│ min        ┆ null       ┆ 1002164    ┆ 32260.0    ┆ … ┆ 0.00   ┆ 1000.14 ┆ null      ┆ null      │
│ 25%        ┆ null       ┆ null       ┆ 1.6540167e ┆ … ┆ null   ┆ null    ┆ null      ┆ null      │
│            ┆            ┆            ┆ 7          ┆   ┆        ┆         ┆           ┆           │
│ 50%        ┆ null       ┆ null       ┆ 1.9310278e ┆ … ┆ null   ┆ null    ┆ null      ┆ null      │
│            ┆            ┆            ┆ 7          ┆   ┆        ┆         ┆           ┆           │
│ 75%        ┆ null       ┆ null       ┆ 2.5098074e ┆ … ┆ null   ┆ null    ┆ null      ┆ null      │
│            ┆            ┆            ┆ 7          ┆   ┆        ┆         ┆           ┆           │
│ max        ┆ null       ┆ Not Determ ┆ 2.9025719e ┆ … ┆ 99.97  ┆ 995.19  ┆ null      ┆ null      │
│            ┆            ┆ ined(Insol ┆ 7          ┆   ┆        ┆         ┆           ┆           │
│            ┆            ┆ uble)      ┆            ┆   ┆        ┆         ┆           ┆           │
└────────────┴────────────┴────────────┴────────────┴───┴────────┴─────────┴───────────┴───────────┘

In [7]:
df.head()

shape: (5, 57)
┌────────────┬────────────┬────────────┬────────────┬───┬───────┬────────┬────────────┬────────────┐
│ action_typ ┆ activity_c ┆ activity_i ┆ activity_p ┆ … ┆ psa   ┆ mw     ┆ ecfp_smile ┆ fingerprin │
│ e          ┆ omment     ┆ d          ┆ roperties  ┆   ┆ ---   ┆ ---    ┆ s          ┆ t          │
│ ---        ┆ ---        ┆ ---        ┆ ---        ┆   ┆ str   ┆ str    ┆ ---        ┆ ---        │
│ struct[3]  ┆ str        ┆ i64        ┆ list[struc ┆   ┆       ┆        ┆ list[i64]  ┆ list[i64]  │
│            ┆            ┆            ┆ t[12]]     ┆   ┆       ┆        ┆            ┆            │
╞════════════╪════════════╪════════════╪════════════╪═══╪═══════╪════════╪════════════╪════════════╡
│ null       ┆ null       ┆ 32260      ┆ []         ┆ … ┆ 82.70 ┆ 383.81 ┆ [0, 0, …   ┆ [0, 0, …   │
│            ┆            ┆            ┆            ┆   ┆       ┆        ┆ 1]         ┆ 1]         │
│ null       ┆ null       ┆ 32260      ┆ []         ┆ … ┆ 82.70 ┆ 383.81 ┆ [0, 0, …   ┆ [0, 0, …   │
│            ┆            ┆            ┆            ┆   ┆       ┆        ┆ 1]         ┆ 1]         │
│ null       ┆ null       ┆ 32260      ┆ []         ┆ … ┆ 82.70 ┆ 383.81 ┆ [0, 0, …   ┆ [0, 0, …   │
│            ┆            ┆            ┆            ┆   ┆       ┆        ┆ 1]         ┆ 1]         │
│ null       ┆ null       ┆ 32263      ┆ []         ┆ … ┆ 82.70 ┆ 383.81 ┆ [0, 0, …   ┆ [0, 0, …   │
│            ┆            ┆            ┆            ┆   ┆       ┆        ┆ 1]         ┆ 1]         │
│ null       ┆ null       ┆ 32263      ┆ []         ┆ … ┆ 82.70 ┆ 383.81 ┆ [0, 0, …   ┆ [0, 0, …   │
│            ┆            ┆            ┆            ┆   ┆       ┆        ┆ 1]         ┆ 1]         │
└────────────┴────────────┴────────────┴────────────┴───┴───────┴────────┴────────────┴────────────┘