In [73]:
#import torch
import sys
sys.path.append('..')

import numpy as np
import polars as pl
import pandas as pd
from rdkit import Chem
from rdkit.Chem import AllChem
import importlib
import utils.utils
importlib.reload(utils.utils)
from utils.utils import fetch_chembl_activity_to_polars, fetch_chembl_data_with_properties, ECFP_from_smiles, save_data_to_parquet

In [77]:
df = df_with_properties

In [ ]:
target_id = "CHEMBL2147"
DB_PATH = 'db/chembl_selected_ds.parquet'
df = get_data_from_parquet(f"{target_id}_IC50.parquet")
#df = None

if df is None:
    df = fetch_chembl_data_with_properties(target_id = target_id)
    save_data_to_parquet(df, file_path = f"{target_id}_IC50.parquet")

Pobieranie aktywności dla celu: CHEMBL2147...
Pobieranie właściwości dla 4142 unikalnych cząsteczek...

[17:07:56] DEPRECATION WARNING: please use MorganGenerator
[17:07:56] DEPRECATION WARNING: please use MorganGenerator
[17:07:56] DEPRECATION WARNING: please use MorganGenerator
[17:07:56] DEPRECATION WARNING: please use MorganGenerator
[17:07:56] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:57] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator
[17:07:58] DEPRECATION WARNING: please use MorganGenerator

Nie ma danych do zapisania.

In [78]:
df.describe()

shape: (9, 17)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sta ┆ mol ┆ can ┆ mol ┆ sta ┆ sta ┆ sta ┆ tar ┆ hbd ┆ hba ┆ psa ┆ mw  ┆ pch ┆ ecf ┆ nod ┆ edg ┆ edg │
│ tis ┆ ecu ┆ oni ┆ ecu ┆ nda ┆ nda ┆ nda ┆ get ┆ --- ┆ --- ┆ --- ┆ --- ┆ emb ┆ p_s ┆ e_f ┆ e_i ┆ e_f │
│ tic ┆ le_ ┆ cal ┆ le_ ┆ rd_ ┆ rd_ ┆ rd_ ┆ _or ┆ f64 ┆ f64 ┆ str ┆ str ┆ l_v ┆ mil ┆ eat ┆ nde ┆ eat │
│ --- ┆ che ┆ _sm ┆ pre ┆ val ┆ uni ┆ rel ┆ gan ┆     ┆     ┆     ┆     ┆ alu ┆ es  ┆ ure ┆ x   ┆ ure │
│ str ┆ mbl ┆ ile ┆ f_n ┆ ue  ┆ ts  ┆ ati ┆ ism ┆     ┆     ┆     ┆     ┆ e   ┆ --- ┆ s   ┆ --- ┆ s   │
│     ┆ _id ┆ s   ┆ ame ┆ --- ┆ --- ┆ on  ┆ --- ┆     ┆     ┆     ┆     ┆ --- ┆ f64 ┆ --- ┆ f64 ┆ --- │
│     ┆ --- ┆ --- ┆ --- ┆ f64 ┆ str ┆ --- ┆ str ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆ f64 ┆     ┆ f64 │
│     ┆ str ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ cou ┆ 668 ┆ 668 ┆ 134 ┆ 666 ┆ 666 ┆ 666 ┆ 668 ┆ 668 ┆ 668 ┆ 668 ┆ 668 ┆ 666 ┆ 668 ┆ 668 ┆ 668 ┆ 668 │
│ nt  ┆ 6   ┆ 5   ┆     ┆ 3.0 ┆ 3   ┆ 3   ┆ 6   ┆ 5.0 ┆ 5.0 ┆ 5   ┆ 5   ┆ 3.0 ┆ 5.0 ┆ 5.0 ┆ 5.0 ┆ 5.0 │
│ nul ┆ 0   ┆ 1   ┆ 655 ┆ 23. ┆ 23  ┆ 23  ┆ 0   ┆ 1.0 ┆ 1.0 ┆ 1   ┆ 1   ┆ 23. ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 │
│ l_c ┆     ┆     ┆ 2   ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     │
│ oun ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ mea ┆ nul ┆ nul ┆ nul ┆ 185 ┆ nul ┆ nul ┆ nul ┆ 2.2 ┆ 5.8 ┆ nul ┆ nul ┆ 7.5 ┆ nul ┆ nul ┆ nul ┆ nul │
│ n   ┆ l   ┆ l   ┆ l   ┆ 23. ┆ l   ┆ l   ┆ l   ┆ 445 ┆ 474 ┆ l   ┆ l   ┆ 110 ┆ l   ┆ l   ┆ l   ┆ l   │
│     ┆     ┆     ┆     ┆ 454 ┆     ┆     ┆     ┆ 77  ┆ 2   ┆     ┆     ┆ 85  ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ 495 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ std ┆ nul ┆ nul ┆ nul ┆ 964 ┆ nul ┆ nul ┆ nul ┆ 0.9 ┆ 1.6 ┆ nul ┆ nul ┆ 1.2 ┆ nul ┆ nul ┆ nul ┆ nul │
│     ┆ l   ┆ l   ┆ l   ┆ 922 ┆ l   ┆ l   ┆ l   ┆ 206 ┆ 099 ┆ l   ┆ l   ┆ 825 ┆ l   ┆ l   ┆ l   ┆ l   │
│     ┆     ┆     ┆     ┆ .52 ┆     ┆     ┆     ┆ 32  ┆ 43  ┆     ┆     ┆ 52  ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ 552 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ min ┆ CHE ┆ Brc ┆ A-4 ┆ 0.0 ┆ nM  ┆ <   ┆ Hom ┆ 0.0 ┆ 0.0 ┆ 100 ┆ 162 ┆ 1.2 ┆ nul ┆ nul ┆ nul ┆ nul │
│     ┆ MBL ┆ 1c( ┆ 85  ┆ 06  ┆     ┆     ┆ o   ┆     ┆     ┆ .03 ┆ .14 ┆ 478 ┆ l   ┆ l   ┆ l   ┆ l   │
│     ┆ 103 ┆ Br) ┆     ┆     ┆     ┆     ┆ sap ┆     ┆     ┆     ┆     ┆ 67  ┆     ┆     ┆     ┆     │
│     ┆ 667 ┆ c(B ┆     ┆     ┆     ┆     ┆ ien ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ r)c ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 2[n ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ H]c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ (N3 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ C=N ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ C4C ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ CCC ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ C43 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ )nc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 2c1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ Br  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 25% ┆ nul ┆ nul ┆ nul ┆ 6.0 ┆ nul ┆ nul ┆ nul ┆ 2.0 ┆ 5.0 ┆ nul ┆ nul ┆ 6.8 ┆ nul ┆ nul ┆ nul ┆ nul │
│     ┆ l   ┆ l   ┆ l   ┆     ┆ l   ┆ l   ┆ l   ┆     ┆     ┆ l   ┆ l   ┆ 268 ┆ l   ┆ l   ┆ l   ┆ l   │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 14  ┆     ┆     ┆     ┆     │
│ 50% ┆ nul ┆ nul ┆ nul ┆ 18. ┆ nul ┆ nul ┆ nul ┆ 2.0 ┆ 6.0 ┆ nul ┆ nul ┆ 7.7 ┆ nul ┆ nul ┆ nul ┆ nul │
│     ┆ l   ┆ l   ┆ l   ┆ 84  ┆ l   ┆ l   ┆ l   ┆     ┆     ┆ l   ┆ l   ┆ 249 ┆ l   ┆ l   ┆ l   ┆ l   │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 19  ┆     ┆     ┆     ┆     │
│ 75% ┆ nul ┆ nul ┆ nul ┆ 149 ┆ nul ┆ nul ┆ nul ┆ 3.0 ┆ 7.0 ┆ nul ┆ nul ┆ 8.2 ┆ nul ┆ nul ┆ nul ┆ nul │
│     ┆ l   ┆ l   ┆ l   ┆ .0  ┆ l   ┆ l   ┆ l   ┆     ┆     ┆ l   ┆ l   ┆ 218 ┆ l   ┆ l   ┆ l   ┆ l   │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 49  ┆     ┆     ┆     ┆     │
│ max ┆ CHE ┆ c1n ┆ UPA ┆ 5.6 ┆ nM  ┆ ~   ┆ Hom ┆ 8.0 ┆ 12. ┆ 99. ┆ 701 ┆ 11. ┆ nul ┆ nul ┆ nul ┆ nul │
│     ┆ MBL ┆ cc( ┆ DAC ┆ 511 ┆     ┆     ┆ o   ┆     ┆ 0   ┆ 97  ┆ .60 ┆ 221 ┆ l   ┆ l   ┆ l   ┆ l   │
│     ┆ 983 ┆ -c2 ┆ ITI ┆ e7  ┆     ┆     ┆ sap ┆     ┆     ┆     ┆     ┆ 849 ┆     ┆     ┆     ┆     │
│     ┆ 50  ┆ ccc ┆ NIB ┆     ┆     ┆     ┆ ien ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 3[n ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ H]c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ c(- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ c4c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ cc( ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ N5C ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ CNC ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ C5) ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ cc4 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ )c3 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ c2) ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ cn1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

In [81]:
df.head()

shape: (5, 16)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬────────┐
│ mol ┆ can ┆ mol ┆ sta ┆ sta ┆ sta ┆ tar ┆ hbd ┆ hba ┆ psa ┆ mw  ┆ pch ┆ ecf ┆ nod ┆ edg ┆ edge_f │
│ ecu ┆ oni ┆ ecu ┆ nda ┆ nda ┆ nda ┆ get ┆ --- ┆ --- ┆ --- ┆ --- ┆ emb ┆ p_s ┆ e_f ┆ e_i ┆ eature │
│ le_ ┆ cal ┆ le_ ┆ rd_ ┆ rd_ ┆ rd_ ┆ _or ┆ i64 ┆ i64 ┆ str ┆ str ┆ l_v ┆ mil ┆ eat ┆ nde ┆ s      │
│ che ┆ _sm ┆ pre ┆ val ┆ uni ┆ rel ┆ gan ┆     ┆     ┆     ┆     ┆ alu ┆ es  ┆ ure ┆ x   ┆ ---    │
│ mbl ┆ ile ┆ f_n ┆ ue  ┆ ts  ┆ ati ┆ ism ┆     ┆     ┆     ┆     ┆ e   ┆ --- ┆ s   ┆ --- ┆ list[l │
│ _id ┆ s   ┆ ame ┆ --- ┆ --- ┆ on  ┆ --- ┆     ┆     ┆     ┆     ┆ --- ┆ lis ┆ --- ┆ lis ┆ ist[i6 │
│ --- ┆ --- ┆ --- ┆ f64 ┆ str ┆ --- ┆ str ┆     ┆     ┆     ┆     ┆ f64 ┆ t[i ┆ lis ┆ t[l ┆ 4]]    │
│ str ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ 64] ┆ t[l ┆ ist ┆        │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ist ┆ [i6 ┆        │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ [i6 ┆ 4]] ┆        │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4]] ┆     ┆        │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪════════╡
│ CHE ┆ CCC ┆ ALO ┆ 100 ┆ nM  ┆ >   ┆ Hom ┆ 2   ┆ 3   ┆ 61. ┆ 267 ┆ 5.0 ┆ [0, ┆ [[0 ┆ [[0 ┆ [[0,   │
│ MBL ┆ Cc1 ┆ ISI ┆ 00. ┆     ┆     ┆ o   ┆     ┆     ┆ 80  ┆ .33 ┆     ┆ 0,  ┆ ,   ┆ ,   ┆ 0, …   │
│ 756 ┆ c(- ┆ NE  ┆ 0   ┆     ┆     ┆ sap ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ 2,  ┆ 1], ┆ 0],    │
│ 80  ┆ c2c ┆ A   ┆     ┆     ┆     ┆ ien ┆     ┆     ┆     ┆     ┆     ┆ 0]  ┆ …   ┆ [1, ┆ [0, 0, │
│     ┆ cc( ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1], ┆ 0], ┆ … 0],  │
│     ┆ O)c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ [0, ┆ …   ┆ … [3,  │
│     ┆ c2) ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2,  ┆ [14 ┆ 0, …   │
│     ┆ [nH ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ ,   ┆ 1]]    │
│     ┆ ]c2 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2], ┆ 19] ┆        │
│     ┆ ncc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ ]   ┆        │
│     ┆ nc1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ [0, ┆     ┆        │
│     ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1,  ┆     ┆        │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆     ┆        │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3]] ┆     ┆        │
│ CHE ┆ CN( ┆ GF- ┆ 27. ┆ nM  ┆ =   ┆ Hom ┆ 2   ┆ 4   ┆ 70. ┆ 412 ┆ 7.5 ┆ [0, ┆ [[0 ┆ [[0 ┆ [[0,   │
│ MBL ┆ C)C ┆ 109 ┆ 0   ┆     ┆     ┆ o   ┆     ┆     ┆ 13  ┆ .49 ┆ 686 ┆ 0,  ┆ ,   ┆ ,   ┆ 0, …   │
│ 746 ┆ CCn ┆ 203 ┆     ┆     ┆     ┆ sap ┆     ┆     ┆     ┆     ┆ 36  ┆ …   ┆ 2,  ┆ 1], ┆ 0],    │
│ 3   ┆ 1cc ┆     ┆     ┆     ┆     ┆ ien ┆     ┆     ┆     ┆     ┆     ┆ 0]  ┆ …   ┆ [1, ┆ [0, 0, │
│     ┆ (C2 ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1], ┆ 0], ┆ … 0],  │
│     ┆ =C( ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ [1, ┆ …   ┆ … [3,  │
│     ┆ c3c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2,  ┆ [14 ┆ 0, …   │
│     ┆ [nH ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ ,   ┆ 1]]    │
│     ┆ ]c4 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3], ┆ 19] ┆        │
│     ┆ ccc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ ]   ┆        │
│     ┆ cc3 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ [0, ┆     ┆        │
│     ┆ 4)C ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1,  ┆     ┆        │
│     ┆ (=O ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆     ┆        │
│     ┆ )NC ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3]] ┆     ┆        │
│     ┆ 2=O ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆ )c2 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆ ccc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆ cc2 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│ CHE ┆ O=c ┆ QUE ┆ 43. ┆ nM  ┆ =   ┆ Hom ┆ 5   ┆ 7   ┆ 131 ┆ 302 ┆ 7.3 ┆ [0, ┆ [[2 ┆ [[0 ┆ [[1,   │
│ MBL ┆ 1c( ┆ RCE ┆ 0   ┆     ┆     ┆ o   ┆     ┆     ┆ .36 ┆ .24 ┆ 665 ┆ 0,  ┆ ,   ┆ ,   ┆ 0, …   │
│ 50  ┆ O)c ┆ TIN ┆     ┆     ┆     ┆ sap ┆     ┆     ┆     ┆     ┆ 32  ┆ …   ┆ 1,  ┆ 1], ┆ 0],    │
│     ┆ (-c ┆     ┆     ┆     ┆     ┆ ien ┆     ┆     ┆     ┆     ┆     ┆ 0]  ┆ …   ┆ [1, ┆ [1, 0, │
│     ┆ 2cc ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1], ┆ 0], ┆ … 0],  │
│     ┆ c(O ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ [0, ┆ …   ┆ … [3,  │
│     ┆ )c( ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1,  ┆ [14 ┆ 0, …   │
│     ┆ O)c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ ,   ┆ 1]]    │
│     ┆ 2)o ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3], ┆ 21] ┆        │
│     ┆ c2c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ ]   ┆        │
│     ┆ c(O ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ [0, ┆     ┆        │
│     ┆ )cc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1,  ┆     ┆        │
│     ┆ (O) ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆     ┆        │
│     ┆ c12 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3]] ┆     ┆        │
│ CHE ┆ CC( ┆ nul ┆ 61. ┆ nM  ┆ =   ┆ Hom ┆ 1   ┆ 5   ┆ 59. ┆ 306 ┆ 7.2 ┆ [0, ┆ [[0 ┆ [[0 ┆ [[0,   │
│ MBL ┆ =O) ┆ l   ┆ 0   ┆     ┆     ┆ o   ┆     ┆     ┆ 29  ┆ .37 ┆ 146 ┆ 0,  ┆ ,   ┆ ,   ┆ 0, …   │
│ 200 ┆ c1c ┆     ┆     ┆     ┆     ┆ sap ┆     ┆     ┆     ┆     ┆ 7   ┆ …   ┆ 2,  ┆ 1], ┆ 0],    │
│ 528 ┆ ccc ┆     ┆     ┆     ┆     ┆ ien ┆     ┆     ┆     ┆     ┆     ┆ 0]  ┆ …   ┆ [1, ┆ [0, 0, │
│     ┆ (-c ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1], ┆ 0], ┆ … 0],  │
│     ┆ 2cn ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ [0, ┆ …   ┆ … [0,  │
│     ┆ c3c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1,  ┆ [17 ┆ 0, …   │
│     ┆ cc( ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ ,   ┆ 1]]    │
│     ┆ NCC ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3], ┆ 19] ┆        │
│     ┆ 4CC ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ ]   ┆        │
│     ┆ 4)n ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ [0, ┆     ┆        │
│     ┆ n23 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1,  ┆     ┆        │
│     ┆ )c1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆     ┆        │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2]] ┆     ┆        │
│ CHE ┆ N#C ┆ nul ┆ 50. ┆ nM  ┆ =   ┆ Hom ┆ 2   ┆ 3   ┆ 76. ┆ 367 ┆ 7.3 ┆ [0, ┆ [[1 ┆ [[0 ┆ [[2,   │
│ MBL ┆ c1c ┆ l   ┆ 0   ┆     ┆     ┆ o   ┆     ┆     ┆ 88  ┆ .20 ┆ 010 ┆ 0,  ┆ ,   ┆ ,   ┆ 0, …   │
│ 391 ┆ (-c ┆     ┆     ┆     ┆     ┆ sap ┆     ┆     ┆     ┆     ┆ 3   ┆ …   ┆ 0,  ┆ 1], ┆ 0],    │
│ 586 ┆ 2cc ┆     ┆     ┆     ┆     ┆ ien ┆     ┆     ┆     ┆     ┆     ┆ 0]  ┆ …   ┆ [1, ┆ [2, 0, │
│     ┆ ccc ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1], ┆ 0], ┆ … 0],  │
│     ┆ 2)c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ [0, ┆ …   ┆ … [3,  │
│     ┆ c(- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0,  ┆ [12 ┆ 0, …   │
│     ┆ c2c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ ,   ┆ 1]]    │
│     ┆ c(B ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2], ┆ 18] ┆        │
│     ┆ r)c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ ]   ┆        │
│     ┆ cc2 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ [2, ┆     ┆        │
│     ┆ O)[ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1,  ┆     ┆        │
│     ┆ nH] ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆     ┆        │
│     ┆ c1= ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1]] ┆     ┆        │
│     ┆ O   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴────────┘

In [ ]:
# Szybkie sprawdzenie poprawności wyników:
display(df.select(pl.col("pchembl_value")).describe())

shape: (9, 2)
┌────────────┬───────────────┐
│ statistic  ┆ pchembl_value │
│ ---        ┆ ---           │
│ str        ┆ f64           │
╞════════════╪═══════════════╡
│ count      ┆ 6663.0        │
│ null_count ┆ 23.0          │
│ mean       ┆ 7.511085      │
│ std        ┆ 1.282552      │
│ min        ┆ 1.247867      │
│ 25%        ┆ 6.826814      │
│ 50%        ┆ 7.724919      │
│ 75%        ┆ 8.221849      │
│ max        ┆ 11.221849     │
└────────────┴───────────────┘

In [103]:
import polars as pl


df_deduplicated = (
    df
    # 1. Obieramy sobie unikatowy łańcuch molekularny za fundament (każdy unikatowy SMILES będzie reprezentował dokładnie 1 docelowy wiersz)
    .group_by("canonical_smiles")
    # 2. Narzucamy zasady, co zrobić z dziesiątkami kolumn duplikatów:
    .agg([
        # Dla wartości pomiarowych (targetu iIC50/pChEMBL) bierzemy MEDIANĘ (jest wysoce odporna na odskakujące, obłędne błędy i daje solidny werdykt ze wszystkich laboratoriów)
        pl.col("pchembl_value").median().alias("pchembl_value"),
        
        # Właściwości chemiczne (masa gęstość itp.) zawsze będą takie same dla tej samej cząsteczki, więc pobieramy po prostu jej pierwszą wartość ze spiętrzonego stosu zduplikowanych zgłoszeń 
        pl.col("mw").first(),
        pl.col("psa").first(),
        pl.col("hbd").first(),
        pl.col("hba").first(),
        pl.col("ecfp_smiles").first(),      # Jeżeli jest już wygenerowany, to pierwszy z góry będzie OK!
        
        # Opcjonalnie: Zliczenie ile duplikatów zebrało się na ten jeden wynik (na wypadek chęci analizy rozbieżności, kto by chciał)
        pl.col("pchembl_value").count().alias("measurements_merged_count")
    ])
)

print(f"Stworzono doskonały zbiór gotowy dla Modelu AI zredukowany do {df_deduplicated.shape[0]} w pełni unikalnych atomowo rzędów!")

Stworzono doskonały zbiór gotowy dla Modelu AI zredukowany do 4142 w pełni unikalnych atomowo rzędów!

In [106]:
from utils.utils import save_data_to_parquet

# Używamy tej samej wywoływanej wcześniej ścieżki - archiwizujemy pierwotny i budujemy nowy plik
destination_path = f"{target_id}_cleaned.parquet"

save_data_to_parquet(df, file_path=destination_path)
print(f"Dane pomyślnie zapisane do {destination_path}. Możesz teraz odczytywać je bezpośrednio stąd w swoim Skrypcie model.ipynb.")

Zapisywanie danych do pliku: CHEMBL2147_cleaned.parquet
Dane pomyślnie zapisane do CHEMBL2147_cleaned.parquet. Możesz teraz odczytywać je bezpośrednio stąd w swoim Skrypcie model.ipynb.

In [107]:
from utils.utils import save_data_to_parquet

# Używamy tej samej wywoływanej wcześniej ścieżki - archiwizujemy pierwotny i budujemy nowy plik
destination_path = f"{target_id}_deduplicated.parquet"

save_data_to_parquet(df_deduplicated, file_path=destination_path)
print(f"Dane pomyślnie zapisane do {destination_path}. Możesz teraz odczytywać je bezpośrednio stąd w swoim Skrypcie model.ipynb.")

Zapisywanie danych do pliku: CHEMBL2147_deduplicated.parquet
Dane pomyślnie zapisane do CHEMBL2147_deduplicated.parquet. Możesz teraz odczytywać je bezpośrednio stąd w swoim Skrypcie model.ipynb.